name: Deploy to IIS (No Username & Password)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Publish Project
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
  staging:
    runs-on: self-hosted  # Uses IIS server as runner
    needs: build
    environment:
      name: staging
    steps:

    - name: Staging Deployment
      shell: powershell
      run: |
        Write-Host "✅ Deployment Staging Successful!"
  production:
    runs-on: self-hosted  # Uses IIS server as runner
    needs: staging
    environment:
      name: production
    steps:
    - name: Production Deployment
      shell: powershell
      run: |
        Write-Host "Deployment Successful!"
